"""Stage 7 against the live warehouse, with a fake model.

The provider is faked; nothing else is. These run against real Stage 5 evidence
and real Stage 6 decisions, because the properties being tested are about how
Stage 7 behaves around them - eligibility, idempotency, and above all the
guarantee that no Stage 7 outcome, including total provider failure, can alter a
Stage 6 decision.

Skipped automatically when the stack is not running.

Every test that writes cleans up after itself by deleting only the rows it
created, keyed on a test-only model name. The live 90-day dataset is left as it
was found.
"""

from __future__ import annotations

import os
import pathlib
from datetime import date

import pytest

from analytics import repository
from analytics.config import Settings
from analytics.llm import prompts, service
from analytics.llm.provider import ProviderError, StaticProvider
from tests.llm_fixtures import valid_response

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]

LIVE_CRITICAL = date(2026, 8, 5)
LIVE_MAJOR = date(2026, 8, 9)
LIVE_NORMAL_SUNDAY = date(2026, 8, 2)

# Test-only model names, so cleanup can target exactly what a test created and
# nothing generated by a real run.
TEST_MODEL = "test-model-stage7"
OTHER_MODEL = "test-model-stage7-alt"
TEST_PROMPT_VERSION = "stage7-prompt-v99"


def _load_env_file() -> dict[str, str]:
    env_path = REPO_ROOT / ".env"
    if not env_path.exists():
        return {}

    values: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


@pytest.fixture(scope="session")
def settings() -> Settings:
    env_file = _load_env_file()

    password = os.getenv("ANALYTICS_DB_PASSWORD") or env_file.get("POSTGRES_PASSWORD")
    if not password:
        pytest.skip("No database password available - is the stack configured?")

    return Settings(
        host=os.getenv("ANALYTICS_DB_HOST", "localhost"),
        port=int(os.getenv("ANALYTICS_DB_PORT") or env_file.get("POSTGRES_HOST_PORT") or 5432),
        database=os.getenv("ANALYTICS_DB_NAME") or env_file.get("POSTGRES_DB") or "salesops",
        user=os.getenv("ANALYTICS_DB_USER") or env_file.get("POSTGRES_USER") or "salesops",
        password=password,
    )


@pytest.fixture(scope="session")
def connection(settings: Settings):
    try:
        conn = repository.connect(settings.dsn)
    except Exception as exc:  # noqa: BLE001 - any failure means "no stack"
        pytest.skip(f"Warehouse not reachable ({exc}) - is the stack running?")

    with conn:
        yield conn


@pytest.fixture(autouse=True)
def clean_test_hypotheses(connection):
    """Remove only what these tests create, before and after each one."""
    def purge():
        with connection.cursor() as cursor:
            cursor.execute(
                "DELETE FROM salesops.anomaly_hypotheses WHERE model_name IN (%s, %s)",
                (TEST_MODEL, OTHER_MODEL),
            )
        connection.commit()

    purge()
    yield
    purge()


def query(connection, sql: str, params: dict | None = None) -> list[dict]:
    with connection.cursor() as cursor:
        cursor.execute(sql, params or {})
        return cursor.fetchall()


def decisions_snapshot(connection) -> list[dict]:
    """Every Stage 6 field Stage 7 must never touch."""
    return query(connection, """
        SELECT decision_id, severity, routing, decision,
               notification_allowed, human_review_required, decision_reason_code
        FROM salesops.anomaly_decisions
        ORDER BY decision_id
    """)


def run(settings, provider, **kwargs):
    return service.run_analysis(settings=settings, provider=provider, **kwargs)


def good_provider(model: str = TEST_MODEL) -> StaticProvider:
    return StaticProvider(payload=valid_response(), model=model)


# =============================================================================
# Eligibility: only actionable anomalies reach a model
# =============================================================================


def test_only_actionable_decisions_are_analysed(settings, connection):
    provider = good_provider()
    summary = run(settings, provider)

    actionable = query(connection, """
        SELECT count(*) AS n FROM salesops.anomaly_decisions
        WHERE decision_version = 'stage6-v1' AND decision = 'action_required'
    """)[0]["n"]

    assert summary.eligible == actionable
    assert summary.succeeded == actionable


def test_no_action_decisions_are_never_sent_to_the_model(settings, connection):
    """The majority of days. Analysing them would spend money to explain that
    nothing happened."""
    provider = good_provider()
    run(settings, provider)

    analysed = {
        row["calendar_date"]
        for row in query(connection, """
            SELECT calendar_date FROM salesops.anomaly_hypotheses WHERE model_name = %(m)s
        """, {"m": TEST_MODEL})
    }

    no_action = {
        row["calendar_date"]
        for row in query(connection, """
            SELECT calendar_date FROM salesops.anomaly_decisions
            WHERE decision_version = 'stage6-v1' AND decision = 'no_action'
        """)
    }

    assert analysed
    assert not (analysed & no_action)
    assert LIVE_NORMAL_SUNDAY not in analysed


def test_unscorable_dates_are_never_analysed(settings, connection):
    provider = good_provider()
    run(settings, provider)

    leaked = query(connection, """
        SELECT h.calendar_date
        FROM salesops.anomaly_hypotheses h
        JOIN salesops.anomaly_decisions d ON d.decision_id = h.decision_id
        WHERE h.model_name = %(m)s AND d.baseline_status <> 'scored'
    """, {"m": TEST_MODEL})

    assert leaked == []


def test_the_model_is_called_exactly_once_per_eligible_anomaly(settings):
    provider = good_provider()
    summary = run(settings, provider)

    assert len(provider.calls) == summary.eligible


def test_a_specific_date_can_be_targeted(settings):
    provider = good_provider()
    summary = run(settings, provider, only_dates=[LIVE_CRITICAL])

    assert summary.eligible == 1
    assert summary.succeeded == 1
    assert summary.analysed_dates == [LIVE_CRITICAL.isoformat()]


def test_the_limit_caps_work_without_hiding_it(settings, caplog):
    """A silent cap reads as 'we covered everything'."""
    import logging
    caplog.set_level(logging.WARNING)

    summary = run(settings, good_provider(), limit=1)

    assert summary.succeeded == 1
    assert "not analysed" in caplog.text


# =============================================================================
# Stage 6 is untouched - by success, and by every kind of failure
# =============================================================================


@pytest.mark.parametrize(
    "provider",
    [
        pytest.param(good_provider(), id="success"),
        pytest.param(StaticProvider(error=ProviderError("timed out"), model=TEST_MODEL),
                     id="timeout"),
        pytest.param(StaticProvider(error=RuntimeError("boom"), model=TEST_MODEL),
                     id="unexpected-exception"),
        pytest.param(StaticProvider(payload="{malformed", model=TEST_MODEL),
                     id="malformed-json"),
        pytest.param(StaticProvider(payload={"summary": "incomplete"}, model=TEST_MODEL),
                     id="schema-violation"),
        pytest.param(StaticProvider(payload=None, model=TEST_MODEL), id="empty-response"),
    ],
)
def test_no_stage6_decision_changes_whatever_the_model_does(settings, connection, provider):
    """The load-bearing test of the entire stage.

    Whatever the model returns - or fails to return - severity, routing,
    decision, notification permission and the review requirement are exactly as
    they were. Stage 7 has no code path that writes to anomaly_decisions; this
    asserts the absence against the live table.
    """
    before = decisions_snapshot(connection)

    run(settings, provider)

    assert decisions_snapshot(connection) == before


def test_a_failing_provider_writes_no_hypotheses(settings, connection):
    provider = StaticProvider(error=ProviderError("gateway error"), model=TEST_MODEL)

    summary = run(settings, provider)

    assert summary.failed == summary.processed > 0
    assert summary.succeeded == 0
    assert query(connection, """
        SELECT count(*) AS n FROM salesops.anomaly_hypotheses WHERE model_name = %(m)s
    """, {"m": TEST_MODEL})[0]["n"] == 0


def test_a_total_provider_failure_is_reported_failed_not_success(settings):
    summary = run(settings, StaticProvider(error=ProviderError("down"), model=TEST_MODEL))

    assert summary.status == "failed"


def test_an_empty_eligible_set_is_a_success_not_a_failure(settings):
    """A healthy week with nothing actionable is not a fault."""
    summary = run(settings, good_provider(), decision_version="stage6-does-not-exist")

    assert summary.eligible == 0
    assert summary.status == "success"


def test_failures_name_the_dates_that_failed(settings):
    summary = run(settings, StaticProvider(error=ProviderError("nope"), model=TEST_MODEL))

    assert summary.failures
    for failure in summary.failures:
        assert failure.calendar_date
        assert failure.reason


def test_a_failure_reason_carries_no_credentials(settings):
    provider = StaticProvider(
        error=ProviderError("HTTP 401: invalid api key"), model=TEST_MODEL
    )
    summary = run(settings, provider)

    for failure in summary.failures:
        assert "sk-" not in failure.reason
        assert "authorization" not in failure.reason.lower()


# =============================================================================
# Persistence and provenance
# =============================================================================


def test_a_valid_hypothesis_is_persisted_with_full_provenance(settings, connection):
    run(settings, good_provider(), only_dates=[LIVE_CRITICAL])

    row = query(connection, """
        SELECT * FROM salesops.anomaly_hypotheses
        WHERE model_name = %(m)s AND calendar_date = %(d)s
    """, {"m": TEST_MODEL, "d": LIVE_CRITICAL})[0]

    assert row["model_provider"] == "mock"
    assert row["model_name"] == TEST_MODEL
    assert row["prompt_version"] == prompts.PROMPT_VERSION
    assert row["evidence_digest"] and len(row["evidence_digest"]) == 64
    assert row["generated_at"] is not None
    assert row["confidence"] in {"low", "medium", "high"}
    assert row["summary"].strip()
    assert row["primary_hypothesis"].strip()


def test_structured_lists_are_stored_as_json_arrays(settings, connection):
    run(settings, good_provider(), only_dates=[LIVE_CRITICAL])

    row = query(connection, """
        SELECT jsonb_typeof(supporting_evidence)    AS s,
               jsonb_typeof(alternative_hypotheses) AS a,
               jsonb_typeof(missing_evidence)       AS m,
               jsonb_typeof(recommended_checks)     AS r,
               jsonb_array_length(supporting_evidence) AS n
        FROM salesops.anomaly_hypotheses
        WHERE model_name = %(m)s AND calendar_date = %(d)s
    """, {"m": TEST_MODEL, "d": LIVE_CRITICAL})[0]

    assert (row["s"], row["a"], row["m"], row["r"]) == ("array",) * 4
    assert row["n"] > 0


def test_the_stored_snapshot_matches_the_live_stage6_decision(settings, connection):
    run(settings, good_provider(), only_dates=[LIVE_CRITICAL])

    row = query(connection, """
        SELECT h.severity, h.routing, h.decision,
               d.severity AS d_severity, d.routing AS d_routing, d.decision AS d_decision
        FROM salesops.anomaly_hypotheses h
        JOIN salesops.anomaly_decisions d ON d.decision_id = h.decision_id
        WHERE h.model_name = %(m)s AND h.calendar_date = %(d)s
    """, {"m": TEST_MODEL, "d": LIVE_CRITICAL})[0]

    assert (row["severity"], row["routing"], row["decision"]) == \
           (row["d_severity"], row["d_routing"], row["d_decision"])
    assert row["severity"] == "critical"


def test_the_database_rejects_a_hypothesis_that_restates_the_verdict(settings, connection):
    """Belt and braces behind `extra="forbid"`.

    Even a bug in the service cannot land a hypothesis whose recorded severity
    disagrees with the decision it points at.
    """
    run(settings, good_provider(), only_dates=[LIVE_CRITICAL])

    with pytest.raises(Exception, match="may not restate"):
        with connection.cursor() as cursor:
            cursor.execute("""
                UPDATE salesops.anomaly_hypotheses SET severity = 'minor'
                WHERE model_name = %(m)s AND calendar_date = %(d)s
            """, {"m": TEST_MODEL, "d": LIVE_CRITICAL})
    connection.rollback()


def test_the_audit_view_reports_the_snapshot_as_current(settings, connection):
    run(settings, good_provider(), only_dates=[LIVE_CRITICAL])

    row = query(connection, """
        SELECT decision_current, decision_severity, analysed_severity, confidence
        FROM salesops.anomaly_hypothesis_audit
        WHERE calendar_date = %(d)s AND model_name = %(m)s
    """, {"m": TEST_MODEL, "d": LIVE_CRITICAL})[0]

    assert row["decision_current"] is True
    assert row["decision_severity"] == row["analysed_severity"]


# =============================================================================
# Idempotency and regeneration
# =============================================================================


def test_a_second_run_creates_no_duplicates(settings, connection):
    first = run(settings, good_provider())
    second = run(settings, good_provider())

    assert second.succeeded == 0
    assert second.processed == 0
    assert second.skipped_existing == first.succeeded

    duplicates = query(connection, """
        SELECT anomaly_id FROM salesops.anomaly_hypotheses
        WHERE model_name = %(m)s
        GROUP BY anomaly_id, decision_version, prompt_version, model_name
        HAVING count(*) > 1
    """, {"m": TEST_MODEL})

    assert duplicates == []


def test_a_second_run_does_not_call_the_model_again(settings):
    """Idempotency has to be checked before the money is spent, not after."""
    run(settings, good_provider())

    second_provider = good_provider()
    run(settings, second_provider)

    assert second_provider.calls == []


def test_a_new_prompt_version_creates_a_new_row_beside_the_old_one(settings, connection):
    run(settings, good_provider(), only_dates=[LIVE_CRITICAL])
    run(settings, good_provider(), only_dates=[LIVE_CRITICAL],
        prompt_version=TEST_PROMPT_VERSION)

    rows = query(connection, """
        SELECT prompt_version FROM salesops.anomaly_hypotheses
        WHERE model_name = %(m)s AND calendar_date = %(d)s
        ORDER BY prompt_version
    """, {"m": TEST_MODEL, "d": LIVE_CRITICAL})

    assert [row["prompt_version"] for row in rows] == \
           sorted([prompts.PROMPT_VERSION, TEST_PROMPT_VERSION])


def test_a_different_model_creates_a_new_row_beside_the_old_one(settings, connection):
    run(settings, good_provider(TEST_MODEL), only_dates=[LIVE_CRITICAL])
    run(settings, good_provider(OTHER_MODEL), only_dates=[LIVE_CRITICAL])

    rows = query(connection, """
        SELECT model_name FROM salesops.anomaly_hypotheses
        WHERE calendar_date = %(d)s AND model_name IN (%(a)s, %(b)s)
    """, {"d": LIVE_CRITICAL, "a": TEST_MODEL, "b": OTHER_MODEL})

    assert len(rows) == 2


def test_regeneration_replaces_rather_than_duplicating(settings, connection):
    run(settings, good_provider(), only_dates=[LIVE_CRITICAL])

    before = query(connection, """
        SELECT hypothesis_id FROM salesops.anomaly_hypotheses
        WHERE model_name = %(m)s AND calendar_date = %(d)s
    """, {"m": TEST_MODEL, "d": LIVE_CRITICAL})[0]["hypothesis_id"]

    summary = run(settings, good_provider(), only_dates=[LIVE_CRITICAL], regenerate=True)

    after = query(connection, """
        SELECT hypothesis_id FROM salesops.anomaly_hypotheses
        WHERE model_name = %(m)s AND calendar_date = %(d)s
    """, {"m": TEST_MODEL, "d": LIVE_CRITICAL})

    assert summary.succeeded == 1
    assert summary.regenerated == 1
    assert len(after) == 1
    assert after[0]["hypothesis_id"] != before


def test_regeneration_is_never_implicit(settings):
    """The scheduled path must not be able to reach it.

    A nightly job that silently rewrote yesterday's reasoning would destroy the
    audit trail it exists to create.
    """
    import inspect
    signature = inspect.signature(service.run_analysis)

    assert signature.parameters["regenerate"].default is False


# =============================================================================
# What the model was actually shown
# =============================================================================


def test_the_real_evidence_package_carries_live_stage6_context(settings):
    provider = good_provider()
    run(settings, provider, only_dates=[LIVE_CRITICAL])

    _, user_message = provider.calls[0]

    assert "severity            = critical" in user_message
    assert "routing             = human_review" in user_message
    assert "CRITICAL_COMBINED_IMPACT" in user_message
    assert "SEVERE_REFUND_SPIKE" in user_message


def test_the_high_score_case_is_shown_its_real_severity(settings):
    """2026-08-09 scores higher than the critical day and is only major."""
    provider = good_provider()
    run(settings, provider, only_dates=[LIVE_MAJOR])

    _, user_message = provider.calls[0]

    assert "severity            = major" in user_message
    assert "anomaly_score = 12.94" in user_message


def test_no_future_data_reaches_the_model_from_the_live_warehouse(settings):
    """The SQL bounds it; this proves it end to end against real rows."""
    import re

    provider = good_provider()
    run(settings, provider, only_dates=[LIVE_CRITICAL])

    _, user_message = provider.calls[0]
    history_block = user_message.split("HISTORICAL COMPARISON")[1].split("[source:")[0]

    dates = [
        date.fromisoformat(match)
        for match in re.findall(r"\d{4}-\d{2}-\d{2}", history_block)
    ]

    assert dates
    assert all(observed < LIVE_CRITICAL for observed in dates)


def test_a_grounded_response_survives_the_metric_check_against_real_evidence(settings):
    """The fixture cites refund_rate and orders_count; both must really exist."""
    summary = run(settings, good_provider(), only_dates=[LIVE_CRITICAL])

    assert summary.succeeded == 1
    assert summary.failed == 0


def test_an_ungrounded_response_is_rejected_against_real_evidence(settings, connection):
    provider = StaticProvider(
        payload=valid_response(metric="payment_gateway_error_rate"), model=TEST_MODEL
    )

    summary = run(settings, provider, only_dates=[LIVE_CRITICAL])

    assert summary.succeeded == 0
    assert summary.failed == 1
    assert "never provided" in summary.failures[0].reason
    assert query(connection, """
        SELECT count(*) AS n FROM salesops.anomaly_hypotheses WHERE model_name = %(m)s
    """, {"m": TEST_MODEL})[0]["n"] == 0
